### ISSUE TITLE
Unable to import development test data

### ISSUE THREAD

**Issue by jkva** [w3c/aria-at-app#348]
I've successfully set up a local dev/test instance of the application, using the `reporting-integration` branch as was suggested to me in [a comment on another issue.](https://github.com/w3c/aria-at-app/issues/344#issuecomment-953834357)

I've run the database initialisation script, the migration script and the seeding script. The final step as documented in [the database setup instructions](https://github.com/w3c/aria-at-app/blob/3f8b636aad069ff81b70a6690f3e3e01d1b15e16/docs/database.md) is to run `yarn db-import-tests:dev`.

While this command completes without errors, no data seems to be added to my local database. Upon inspecting the actual import script, I saw:

```javascript
const importTestPlanVersions = async () => {
    return;
    // THE TEST IMPORT SCRIPT IS TEMPORARILY DISABLED!
    // This is a preventative measure to protect the integrity of the database
    // with the addition of command sequences in the ARIA-AT repo.
    /* eslint-disable no-unreachable */
```

on [line 49](https://github.com/w3c/aria-at-app/blob/ebd87a7efdfc0883b9587b1546faaab00e4fec51/server/scripts/import-tests/index.js#L49).

It would have saved me some head scratching had something like this been logged to the console when running the script. Combined with an actual linter rule being disabled, as opposed to not running the function at all and instead logging an explanation to the console.

Apart from this, what are the steps I can take to recreate the environment I find at [the sandbox instance of the app](https://aria-at-app-sandbox.bocoup.com/)?

Thank you.

**Comment by jscholes** [comment]
@s3ththompson / @alflennik What are your thoughts on moving forward past this?  If it will be some time before the import script is updated to work as intended, is there the possibility of a database dump (e.g. from the sandbox) that we can work with in the meantime?

**Comment by alflennik** [comment]
Hi @jkva @jscholes, I have a fix, and I just tested it so hopefully it works for you. Please don't be shy if you run into any trouble.

If you comment out the `return` on line 50 of `server/scripts/import-tests/index.js`, then the database setup instructions in `docs/database.md` will work again.

Note that any test plans with command sequences (currently just the Breadcrumb test plan I believe) will not work, but if you just avoid that one, all the other test plans will work fine.

Apologies that it failed silently, causing you to have to dig through the source code. If I knew you were coming I would have cleaned the house 🤓

**Comment by jkva** [comment]
Hi @alflennik, thanks for the response. Commenting out the `return` statement was the first thing I tried, and while the script takes a bit longer to execute (presumably because a repository is being cloned and processed) I did not see any results in my local instance. I also looked through the postgres tables and did not find anything relevant in those.

I also dropped the database and repeated the instructions in `database.md`, no luck.

Is there something I can do to verify that things are working as expected?

**Comment by alflennik** [comment]
Sorry for your trouble @jkva. Let's see if we can figure it out and then improve the docs.

When you run:

```
if [[ "$OSTYPE" == "darwin"* ]]; then
    createdb # run this if the PostgreSQL installation is freshly installed
    yarn db-init:dev;
else
    sudo -u postgres yarn db-init:dev;
fi;
```

You should see the `aria_at_report` database appear.

The next step, `yarn sequelize db:migrate;` should take a second to run. You'll know it succeeded if you see around 15 empty tables and the TestPlanVersion should have a directory column.

`yarn sequelize db:seed:all;` should also take just a second. You'll know it worked if the Ats table is populated with three ATs.

Next, make sure the return statement is commented out, and run `yarn db-import-tests:dev`. You should see `Done, no errors` and something like `Done in 5.72s` as the last lines of the output, and there should now be 21 TestPlanVersions populated in the TestPlanVersion table.

I would say maybe you've already gotten this far?

Okay, so now you can run `yarn dev`, and the app will start running on `http://localhost:3000`. If you go to the Test Queue page without signing in, you should see a `There are no test plans available` message. This is because members of the public can only view the test plans which are currently being tested, and since the database is empty, there is no content to show.

Next, we should get you signed in as an admin. [Instructions for that are here](https://github.com/w3c/aria-at-app/blob/develop/docs/local-development.md#signing-in-as-a-tester-andor-admin), but to summarize, you will change the url to `http://localhost:3000/?fakeRole=admin` and load the page, then sign in with your normal GitHub account.

You will know you successfully logged in as an admin if you come back to the app from GitHub and you see the Test Queue page with a "Add a Test Plan to the Queue" button. That button only appears to admins.

At this point, you can try clicking that button, and a dialog should open where you should be able to pick an AT from the dropdown, make up an AT Version, pick a browser from the browser dropdown, make up a browser version, pick from one of the 21 test plans from the TestPlan dropdown, and select the version we just imported from the TestPlanVersion dropdown. After clicking Add, an entry will appear in the Test Queue.

With the Test Queue populated, you could assign yourself, start testing and recording results and hopefully get doing everything you need to do.

Hopefully that's enough information to fix your issue. Good luck, and I'll be standing by if you have any follow ups.

**Comment by jkva** [comment]
@alflennik the admin part was the missing piece, I can now proceed further! Thank you very much. Closing this.
