### ISSUE TITLE
Data Management Page: Show status of all test plan versions and enable advancement through all working mode phases (P0 UI)

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#652]
Related to #648: Test Plan Status Summary Table

The P0 functionality for the data management page enables:
1. Any user to view the current status of all test plans in the system.
1. Any user to view working mode progress for each test plan, i.e., which phases are complete, when a phase was completed, and which version of a plan completed a phase.
1. Any user to view and access each currently active version of a test plan.
1. Admins to advance a test plan version through phases of the working mode.

**Overview of Columns for Test Plan Status Summary Table**

1. Test Plan
3. Covered AT
4. Overall Status
5. R&D Version
6. Draft Review
7. Candidate Review
8. Recommended Version

**Comment by ccanash** [comment]
Adding a centralised description of the P0 requirements for the table:

#### Test Plan Column Details

* P0 requirement: Show the name of the test plan
* P1 Requirement: The name is a Link to the "Test Plan Versions" page, which  will provide more details about the plan and all its versions. A description of this page will be provided in a separate issue.
* P2 requirement: table is sortable by the values in this column

#### Covered AT Column Details

* P0 requirement: As a near term stopgap, List covered AT. Works for now since we only have 3.
* P1 requirement: Later, we will define categories of AT and show the covered category, how many AT are covered within the category, and a button that popsup the list of them. For example, there could be a button named "3 Desktop Screen Readers" and activating it would open a dialog listing the screen readers.
* P2 requirement: table is sortable and filterable by the values in this column

#### Overall Status Column Details

P0 Requirement: Show the most advanced phase this plan has completed using the following logic:
* If there is a recommended version:
    * Show string "Recommended Since DATE" where DATE is the date on which a version of this plan was first recommended. Note that multiple versions may have progressed to recommended, so this is the date on which the earliest version progressed to recommended.
    * If  there are also versions currently active in any of the candidate, draft, or R&D complete phases, append string "+N New Versions in Progress" where N is the number of phases where a version is active. If N=1, use singular "version".
* else If there is a candidate version:
    * Show string "Candidate Review Started DATE" where DATE is the date on which the candidate review phase began. Note that multiple versions may have progressed to candidate, so this is the date on which the earliest version progressed to candidate.
    * If  there are also versions currently active in either the draft or R&D complete phases, append string "+N New Versions in Progress" where N is the number of phases where a version is active. If N=1, use singular "version".
* else If there is a draft version:
    * Show string "Draft Review Started DATE" where DATE is  the date on which the draft review phase began. Note that multiple versions may have progressed to draft, so this is the date on which the earliest version progressed to draft.
    * If  there is also a version currently active in the draft phase, append string "+1 New Version in Progress".
* else if R&D is complete, show string "R&D Complete on DATE" where DATE is the date from the version identifier of the version that is currently ready for draft review.

**Notes:**
* dates are sufficient; no need for time stamp.
* this column is used in the default sort order described below. The sort function of this column would return the table to its default state.

#### R&D Version Column Details

* P0 requirement: If the latest version of the plan is in the draft, candidate, or recommended  phase, show string "N/A".
* P0 requirement: else If the latest version has completed R&D and has not yet been advanced to draft review, show:
    * Link with text "VERSION_STRING" that  targets the single-page view of the plan. Example: [V22.12.08](https://aria-at.netlify.app/review/alert.html)
    * If current user is an admin, show "Advance to Draft" button. Note that:
        * If there is an earlier version that is draft and that version has some test plan runs in the test queue, this button will run the process for updating existing reports and preserving data for tests that have not changed.
        * if there is an earlier version in the draft phase, this button will sunset that version. This will also sunset any reports completed using that version.

#### Draft Review Column Details

* P0 requirement: If a version of the plan is not in the draft phase and there are no versions in later phases, show string  "Not Started"
* P0 requirement: If a version of the plan is not in the draft phase and there is a version in at least one of candidate or recommended phases, show string "Review of VERSION_STRING completed DATE" where:
    * VERSION_STRING identifies the version that most recently completed draft review.
    * DATE is the date that the version identified by VERSION_STRING completed draft review and advanced to candidate review.
    * Example: "Review of V22.12.08 completed Jan 30, 2023"
* If there is a version currently in the draft phase, show:
    * P0 Requirement: Link with text "VERSION_STRING" that  targets the single-page view of the plan. Example: [V22.12.08](https://aria-at.netlify.app/review/alert.html)
    * P1 requirement: Show a button that opens the test plan report status dialog. The button label and  dialog are described below.
    * P0 requirement: If required reports  are complete and user is an admin, show "Advance to Candidate" button. Note that:
        * If there is an earlier version that is candidate and that version has some test plan runs in the test queue, this button will run the process for updating existing reports and preserving data for tests that have not changed.
        * if there is an earlier version in the candidate phase, this button will sunset that version. This will also sunset any reports completed using that version.

#### Candidate Review Column Details

* P0 requirement: If a version of the plan is not in the candidate phase and there has not yet been a recommended version, show string  "Not Started"
* P0 requirement: If a version of the plan is not in the candidate phase and there is a recommended version, show string "Review of VERSION_STRING completed DATE" where:
    * VERSION_STRING identifies the version that most recently completed candidate review.
    * DATE is the date that the version identified by VERSION_STRING completed draft review and advanced to candidate review.
    * Example: "Review of V22.12.08 completed Jan 30, 2023"
* If there is a version currently in the candidate phase, show:
    * P0 Requirement: Link with text "VERSION_STRING" that  targets the single-page view of the plan. Example: [V22.12.08](https://aria-at.netlify.app/review/alert.html)
    * P0 Requirement: Show string "N Open Review Issues" and if N>=2, append " from N AT" Examples: "3 Open Review Issues from 2 AT" or "0 Open Review Issues"
    * P1 requirement: Show timeline string "Target N days away|past", Examples: "Target 90 days away" or "Target 10 days past"
    * P1 Requirement: If user is admin, the timeline string is a button that opens the change target date dialog.
    * P0 Requirement: Show button "Advance to Recommended" when  the following conditions are met:
        * If there has not yet been a recommended version and open issues = 0 and days in review > 120 and user is admin, show the button.
        * If there is already a recommended version and open review issues = 0 and user is admin, show the button.
        * If there is an earlier version that is recommended and that version has some test plan runs in the test queue, this button will run the process for updating existing reports and preserving data for tests that have not changed.
        * if there is an earlier version in the recommended phase, this button will sunset that version. This will also sunset any reports completed using that version.

#### Recommended Version Column Details

* P0 requirement: If a version of the plan is not in the recommended phase, shows the string  "None Yet"
* If there is a version currently in the recommended  phase, shows:
    * P0 Requirement: Link with text "VERSION_STRING" that  targets the single-page view of the plan. Example: [V22.12.08](https://aria-at.netlify.app/review/alert.html)
    * P0 Requirement: Show string "Approved DATE" where DATE is the date that the currently recommended version was advanced to the recommended phase.
    * P1 requirement: Show a button that opens the test plan report status dialog. The button label and  dialog are described below.

#### Default Table Sort

* First sort by overall status descending: recommended plans, then candidate plans, then draft plans, then R&D complete plans.
* Then sort by test plan name ascending.
* Then sort by Covered AT ascending

**Comment by mcking65** [comment]
I've completed my testing of this feature and want to say thanks again to the whole team!!!  This was a huge lift, and even though I've found some bugs, overall, the implementation is really good. I'm excited to get this into production!
