### ISSUE TITLE
Add filters for the test plan status summary table on the data management page (P2)

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#678]
_Related to #648: Filters._ 

Add a set of quick filter buttons above the table. the label on Each filter will show the filter name and number of table rows it will render.

The filter buttons are:

1. All Plans
2. R&D Complete
3. In Draft Review
4. In Candidate Review
5. Recommended Plans

Note: Because each plan may have multiple versions moving through the process, i.e., a version active in more than one phase at the same time, the set of rows shown by each filter is not unique. Thus, if the label on the all plans button were "All Plans 65", the sum of the numbers shown in the labels of the other buttons will likely be greater than 65.

**Comment by mcking65** [comment]
@stalgiag and @howard-e, thank you; the filters are working well in staging. We can close this issue after deployment.

Note that the data in staging doesn't enable full testing. Because none of the test plans have multiple active versions, I can't test all the filter requirements. We will have sufficient conditions in production sometime in October.

**Comment by ccanash** [comment]
Released to prod
