### ISSUE TITLE
Can't add plans to the test queue in staging

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#740]
I tried to add V22.14.04 of color viewer slider to the test queue with JAWS/Chrome, JAWS/Firefox, and NVDA/Chrome. I tried from both data management page and test queue page. Each time, the system said it was adding the plan to the test queue, but it doesn't get added.

**Comment by ccanash** [comment]
Will triage tomorrow

**Comment by howard-e** [comment]
That must be because those combinations are already "marked as final", as they're displayed for the for the version's Candidate reports. This makes me think we could either:
1. Prevent the combination being added again, OR
2. When an admin does select that combination for that (non-deprecated) version then remove the "marked as final" to allow for it to still be worked on.

This may be subject to future discussion but I get the feeling the latter may be preferred right now. I'll include that change in #715

**Comment by mcking65** [comment]
Verified this issue is resolved in staging.

**Comment by ccanash** [comment]
Released to production.
