### ISSUE TITLE
Update UI in real time to receive the "per-test” status updates: "started" and "error".

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-at-app#820]

**Comment by jugglinmike** [comment]
### Background

As of this writing, the ARIA-AT App user interface currently does not change when the system begins any given response-collection task. Each task is considered "queued" immediately after being created, and it remains in that state until the response-collection system reports the AT response, at which time, the task's status changes to "completed." The goal of this enhancement is to surface information about two other states: the period where the response-collection system is actively working on a given test (i.e. "in progress"), and the period where an exceptional circumstance has forced the system to abort.

Unfortunately, the UI is currently inconsistent in how it describes the "queued" state. On the Test Queue page, it is described as "Queued", while in the Test Plan Run page, it is described as "In Progress by Bot." Although this problem did not motivate the enhancement described by this issue, the solution should address it.

### User interface design requirements

1. Communicate the following states for response-collection tasks (in addition to "queued" and "completed"):
   - "In progress"
   - Halted due to an "error"
2. Update the existing UI to accurately describe the "queued"

### Process for determining which aspects of the UI should be updated

1. Evaluate the existing UI which communicates the status of response-collection tasks
  - Test Queue page: the "Testers" column (e.g. "Responses for 3 of 5 tests recorded")
  - Test Queue page: the "Report Status" column (e.g. "11 Tests Queued")
  - Test Plan Run page: the label for each testing task (e.g. "In Progress by Bot")
2. Identify any additional areas of the UI which should surface this information

**Comment by isaacdurazo** [comment]
Here's an updated mockup of the Test Queue with the new states added.

I am also including a screenshot of the previously proposed states for the Test Run page. It might be worth revisiting these for implementation. When I designed these I think I remembered an issue with using custom icons and having to go with the existing icon library being used on ARIA AT.

![ARIA-AT - Test Queue – 1](https://github.com/w3c/aria-at-app/assets/1379244/a4960d0c-997c-4717-a99f-c9498faaff32)
