### ISSUE TITLE
Trend reports design proposal

### ISSUE THREAD

**Issue by boazsender** [w3c/aria-at-app#963]
This issue describes a design for trend reports to meet the following requirement from the project [readme](https://github.com/orgs/w3c/projects/67/views/1?pane=info):

> Access to reports on specific AT/browser versions: Minimal UI changes that enable publication of reports for a specific AT/browser version and visibility of reports by AT and browser version.

This design proposal consists of two tables outlined below.

## 1) Trend reports table
The trend reports will consist of a summary table of all historical runs, where each row links to a detail table. This summary table will take the place of the existing table at https://aria-at.w3.org/reports which currently displays the lates trun.
### Summary table heading (column names): 
* Test plan version (git sha of test suite)
* One column for every AT/Browser combo
* Date of run

### Summary table rows
* One row for each run
* A check mark in the cell for each AT/Browser combo if the combo was run with a link to that run

## 2) Detail table 
The detail table will be the same as the current table that exists at https://aria-at.w3.org/reports, but reproduced for every historical run and moved to a url dedicated to the git sha of the given run (e.g. https://aria-at.w3.org/reports/runs/$SHA)

**Comment by mcking65** [comment]
I don't understand the base concept underpinning this design. The test plan version and run date are not relevant dimensions of the trend data. The only relevant dimension for any given AT/Browser combination is the version of the AT. In the future, we might also show a trend by browser version. It remains to be determined whether or not browser version trends have any value.

For now, I think we should keep the top-level page as is so that it always shows the latest data. That is still the most important data. We want anyone coming to the site to easily see that information.

One light-weight approach to providing access to data about all versions of an AT that have been tested for a given test plan might be to provide a AT versions summary table at the top of each detailed report page. So, users would continue to see the latest data on the top-level page and on the second-level page. But when they get to the detailed report on a test plan for a given AT/browser combination, they would see a summary of all versions of that AT tested for that plan.

For example, if you are on the [reports page](https://aria-at.w3.org/reports) and follow the link for the Alert Example, you get to a [page showing a summary of the latest data for each AT/browser combination that was tested](https://aria-at.w3.org/report/56291). Then, if you activate the "View Complete Results" button for VoiceOver and Safari, you get to the [detailed report page for that combination](https://aria-at.w3.org/report/56291/targets/204). Currently, that page title does not include a VoiceOver version. In the future, if the test plan is in the recommended phase, the page title would include the version of VoiceOver. At the top of that page, we could have a VoiceOver versions summary table showing a summary of data for all versions of VoiceOver that have been tested. It could have columns for VoiceOver version, MUST HAVE Behaviors, SHOULD HAVE Behaviors, and MAY HAVE Behaviors. Users could see how VoiceOver support for that test plan has changed from version to version by reading down the columns. Each version could be a link to the detailed report for that version.

Side note: it would be helpful if each of the detailed report pages included a copy of the type of summary table that is shown at the second level in the IA. For example, it would be helpful if the [VoiceOver for macOS and Safari for Alert Example report page](https://aria-at.w3.org/report/56291/targets/204) included a copy of the VoiceOver and Safari table from the [Alert Example report page](https://aria-at.w3.org/report/56291).

**Comment by boazsender** [comment]
Sounds good matt. Lets take that approach.

**Comment by isaacdurazo** [comment]
Here's a mockup that matches your proposal including the side note about a copy of the type of summary table that is shown at the second level in the IA. Cc @ccanash  

![ARIA-AT - Trend reports](https://github.com/w3c/aria-at-app/assets/1379244/7860aec0-771d-4ce6-a578-62acef43f090)

**Comment by ccanash** [comment]
Closing as completed, we will start implementation in #1083
