### ISSUE TITLE
Intermittent automation API Error with transactions

### ISSUE THREAD

**Issue by gnarf** [w3c/aria-at-app#983]
While @jugglinmike was testing this weekends issues with the github automation workflow, the job status URL threw an error related to transactions.

https://github.com/bocoup/aria-at-gh-actions-helper/actions/runs/8426667180/job/23075465091#step:3:15

```
SequelizeConnectionAcquireTimeoutError: Operation timeout
    at ConnectionManager.getConnection (/home/aria-bot/aria-at-report/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:204:15)
    at async Transaction.prepareEnvironment (/home/aria-bot/aria-at-report/node_modules/sequelize/lib/transaction.js:85:24)
    at async Sequelize.transaction (/home/aria-bot/aria-at-report/node_modules/sequelize/lib/sequelize.js:499:7)
    at async middleware (/home/aria-bot/aria-at-report/server/middleware/transactionMiddleware.js:30:23)
```

This error happened on the public server for aria-at-app, and the last deployment was on March 11th.

**Comment by gnarf** [comment]
Additional note: We have observed some other intermittent failure states on the app in the last hour, this might of be symptom a deeper server issue

**Comment by gnarf** [comment]
We actually ran into this error twice - https://github.com/bocoup/aria-at-gh-actions-helper/actions/runs/8426935982/job/23076374771#step:3:15 is the second run that hit this error

**Comment by alflennik** [comment]
Thanks for raising this to my attention. Since we added transactions recently I've been paying close attention to any issues and so I wanted to investigate this one quickly.

The code called out in the stack trace looks innocuous enough. It just starts a transaction. It was not initially obvious why a call like that would time out. 

But thinking about it, that line of code is special in that it is the first call to the database. So if the database became unresponsive this would be the first call to fail.

Therefore my current feeling is that this error might indicate some issue with our database, which may or may not be related to transactions at all. That said, transactions are certainly still a candidate for causing havoc until proven otherwise. I think a good next step might be to check the performance strain of running the database - my thinking is along of lines of, is the database sporadically crashing and restarting? Is it possible that a large query is slowing it down so much that it grinds to a halt? This kind of thing.
