### ISSUE TITLE
Develop requirements for AT version selection

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-at-app#996]
Write requirement to enable test admins to select AT version when assigning automated tests.

**Comment by jugglinmike** [comment]
@ccanash, @howard-e, @mcking65, and I hashed out the requirements during a call today:

- "Add Bot Run" only available if required version is supported by the automation subsystem, and if so, the choices of version are further limited by which versions are required
- "Manage Bot Run" -> display the version used

I suggested that the drop-down in "Add Bot Run" should always include all available options and only disable (rather than remove) the ones that aren't appropriate. Matt didn't have strong feelings about this.

Out-of-scope:

- browser version selection (continue to use whatever is available on in the automation environment)
- automated discovery of new AT versions (new AT versions are to be introduced during deployment via explicit database mutations)
